### ISSUE TITLE
data type problem.

### ISSUE THREAD

**Issue by geyan3566** [rjhogan/Adept#10]
Hi,
I'm using `Adept` in my code and I have this kind statement
```
const xdouble a, b;
xdouble lambda1;
lambda1 = 0.5*(std::max(fabs(lambda1),  a*b) - lambda1);
```
But I got this compiling error:
```
 no matching function for call to ‘max(adept::internal::UnaryOperation<double, adept::internal::Fabs, adept::Active<double> >, adept::internal::enable_if<true, adept::internal::BinaryOperation<double, adept::Active<double>, adept::internal::Multiply, adept::Active<double> > >::type’
    lambda1 = 0.5*(std::max(fabs(lambda1), sat_Vn*rhoA) - lambda1);

```
Could you please help me fix this problem?

Thanks,
Ge

**Comment by rjhogan** [comment]
Guess you figured out that you should replace std::max by max because Adept overloads this function and it is not in the std namespace.  (You may need to replace fabs by abs, I can't remember.)

**Comment by geyan3566** [comment]
Yes, I used `std::max<adouble>()` instead.
