### ISSUE TITLE
Stack command problem

### ISSUE THREAD

**Issue by vichampos** [rjhogan/Adept#9]
Hi,

  I am trying to run sample code on the site http://www.met.reading.ac.uk/clouds/adept/, but compiling returns an error with Stack.
reference not set to "adept::Stack::~Stack()"
  What may be happening?

**Comment by rjhogan** [comment]
Hi,

Could you provide the full file you're compiling, the compiler command 
line, compiler version, Adept version, operating system, and full 
compiler output message please?

Thanks,

Robin.

**Comment by vichampos** [comment]
Hi Robin,

I'm using Manjaro linux with gcc 9.1.0

The command used to compile the code is:
g++ teste.cpp -o test 
or
g++ -I /usr/local/include/adept test.cpp -o test

the test.cpp contains the following code:

#include <iostream>
#include <adept_arrays.h>                // include adept.h if array features not required              
int main(int argc, const char** argv) {
  using namespace adept;
  Stack stack;                           // Object to store differential statements
  aVector x(3);                          // Independent variables: active vector with 3 elements
  x << 1.0, 2.0, 3.0;                    // Fill vector x
  stack.new_recording();                 // Clear any existing differential statements
  aReal J = cbrt(sum(abs(x*x*x)));       // Compute dependent variable: L3-norm in this case
  J.set_gradient(1.0);                   // Seed the dependent variable
  stack.reverse();                       // Reverse-mode differentiation
  std::cout << "dJ/dx = "
            << x.get_gradient() << "\n"; // Print the vector of partial derivatives dJ/dx
  return 0;
}

The error is:

/usr/bin/ld: /tmp/ccc2XMO6.o: na função "main":
teste.cpp:(.text+0x233): referência não definida para "adept::Stack::~Stack()"
/usr/bin/ld: teste.cpp:(.text+0x2b3): referência não definida para "adept::Stack::~Stack()"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "adept::internal::StackStorageOrig::push_lhs(int const&)":
teste.cpp:(.text._ZN5adept8internal16StackStorageOrig8push_lhsERKi[_ZN5adept8internal16StackStorageOrig8push_lhsERKi]+0x2f): referência não definida para "adept::internal::StackStorageOrig::grow_statement_stack(int)"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "adept::internal::StackStorageOrig::check_space(int)":
teste.cpp:(.text._ZN5adept8internal16StackStorageOrig11check_spaceEi[_ZN5adept8internal16StackStorageOrig11check_spaceEi]+0x33): referência não definida para "adept::internal::StackStorageOrig::grow_operation_stack(int)"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "adept::Stack::Stack(bool)":
teste.cpp:(.text._ZN5adept5StackC2Eb[_ZN5adept5StackC5Eb]+0x10c): referência não definida para "adept::Stack::activate()"
/usr/bin/ld: teste.cpp:(.text._ZN5adept5StackC2Eb[_ZN5adept5StackC5Eb]+0x14d): referência não definida para "adept::internal::StackStorageOrig::~StackStorageOrig()"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "adept::Stack::register_gradients(int const&)":
teste.cpp:(.text._ZN5adept5Stack18register_gradientsERKi[_ZN5adept5Stack18register_gradientsERKi]+0x1f): referência não definida para "adept::Stack::do_register_gradients(int const&)"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "adept::Stack::unregister_gradient(int const&)":
teste.cpp:(.text._ZN5adept5Stack19unregister_gradientERKi[_ZN5adept5Stack19unregister_gradientERKi]+0x13d): referência não definida para "adept::Stack::unregister_gradient_not_top(int const&)"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "adept::Stack::reverse()":
teste.cpp:(.text._ZN5adept5Stack7reverseEv[_ZN5adept5Stack7reverseEv]+0x14): referência não definida para "adept::Stack::compute_adjoint()"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "TLS wrapper function for adept::_stack_current_thread":
teste.cpp:(.text._ZTWN5adept21_stack_current_threadE[_ZTWN5adept21_stack_current_threadE]+0x21): referência não definida para "adept::_stack_current_thread"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "adept::internal::enable_if<adept::internal::is_floating_point<double>::value, void>::type adept::Stack::set_gradients<double>(int, int, double const*)":
teste.cpp:(.text._ZN5adept5Stack13set_gradientsIdEENS_8internal9enable_ifIXsrNS2_17is_floating_pointIT_EE5valueEvE4typeEiiPKS5_[_ZN5adept5Stack13set_gradientsIdEENS_8internal9enable_ifIXsrNS2_17is_floating_pointIT_EE5valueEvE4typeEiiPKS5_]+0x43): referência não definida para "adept::Stack::initialize_gradients()"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "adept::Array<1, double, false>::print(std::ostream&) const":
teste.cpp:(.text._ZNK5adept5ArrayILi1EdLb0EE5printERSo[_ZNK5adept5ArrayILi1EdLb0EE5printERSo]+0x39): referência não definida para "adept::internal::array_print_empty_before[abi:cxx11]"
/usr/bin/ld: teste.cpp:(.text._ZNK5adept5ArrayILi1EdLb0EE5printERSo[_ZNK5adept5ArrayILi1EdLb0EE5printERSo]+0x48): referência não definida para "adept::internal::array_print_empty_rank"
/usr/bin/ld: teste.cpp:(.text._ZNK5adept5ArrayILi1EdLb0EE5printERSo[_ZNK5adept5ArrayILi1EdLb0EE5printERSo]+0x68): referência não definida para "adept::internal::array_print_empty_after[abi:cxx11]"
/usr/bin/ld: teste.cpp:(.text._ZNK5adept5ArrayILi1EdLb0EE5printERSo[_ZNK5adept5ArrayILi1EdLb0EE5printERSo]+0x80): referência não definida para "adept::internal::vector_print_before[abi:cxx11]"
/usr/bin/ld: teste.cpp:(.text._ZNK5adept5ArrayILi1EdLb0EE5printERSo[_ZNK5adept5ArrayILi1EdLb0EE5printERSo]+0xd5): referência não definida para "adept::internal::vector_separator[abi:cxx11]"
/usr/bin/ld: teste.cpp:(.text._ZNK5adept5ArrayILi1EdLb0EE5printERSo[_ZNK5adept5ArrayILi1EdLb0EE5printERSo]+0x12c): referência não definida para "adept::internal::vector_print_after[abi:cxx11]"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "adept::Array<1, double, true>::resize(int const*)":
teste.cpp:(.text._ZN5adept5ArrayILi1EdLb1EE6resizeEPKi[_ZN5adept5ArrayILi1EdLb1EE6resizeEPKi]+0x149): referência não definida para "adept::internal::array_row_major_order"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "adept::Storage<double>::~Storage()":
teste.cpp:(.text._ZN5adept7StorageIdED2Ev[_ZN5adept7StorageIdED5Ev]+0x45): referência não definida para "adept::Stack::unregister_gradients(int const&, int const&)"
/usr/bin/ld: teste.cpp:(.text._ZN5adept7StorageIdED2Ev[_ZN5adept7StorageIdED5Ev]+0x4b): referência não definida para "adept::internal::n_storage_objects_deleted_"
/usr/bin/ld: teste.cpp:(.text._ZN5adept7StorageIdED2Ev[_ZN5adept7StorageIdED5Ev]+0x54): referência não definida para "adept::internal::n_storage_objects_deleted_"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "adept::Array<1, double, true>::pack_()":
teste.cpp:(.text._ZN5adept5ArrayILi1EdLb1EE5pack_Ev[_ZN5adept5ArrayILi1EdLb1EE5pack_Ev]+0xf): referência não definida para "adept::internal::array_row_major_order"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "adept::Storage<double>::Storage(int, bool)":
teste.cpp:(.text._ZN5adept7StorageIdEC2Eib[_ZN5adept7StorageIdEC5Eib]+0x47): referência não definida para "adept::internal::n_storage_objects_created_"
/usr/bin/ld: teste.cpp:(.text._ZN5adept7StorageIdEC2Eib[_ZN5adept7StorageIdEC5Eib]+0x50): referência não definida para "adept::internal::n_storage_objects_created_"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "adept::Array<1, double, false>::resize(int const*)":
teste.cpp:(.text._ZN5adept5ArrayILi1EdLb0EE6resizeEPKi[_ZN5adept5ArrayILi1EdLb0EE6resizeEPKi]+0x149): referência não definida para "adept::internal::array_row_major_order"
/usr/bin/ld: /tmp/ccc2XMO6.o: na função "adept::Array<1, double, false>::pack_()":
teste.cpp:(.text._ZN5adept5ArrayILi1EdLb0EE5pack_Ev[_ZN5adept5ArrayILi1EdLb0EE5pack_Ev]+0xf): referência não definida para "adept::internal::array_row_major_order"
collect2: error: ld returned 1 exit status


Thanks for your help

**Comment by rjhogan** [comment]
You also need to link to the compiled library with the argument "-ladept" at then end of your command line. It should automatically look in /usr/local/lib where the libadept.so file is probably located.

--
Professor Robin J. Hogan
Department of Meteorology
University of Reading
PO Box 243
READING RG6 6BB, UK

http://www.met.reading.ac.uk/~swrhgnrj/
https://www.ecmwf.int/en/staff/robin-hogan
________________________________
